import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { resolve } from 'path';

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      // Allow importing `@solver/solver.js` from both app code and workers
      '@solver': resolve(__dirname, 'crates/solver/pkg'),
    },
  },
  // Treat .wasm files generated by wasm-pack as static assets so Vite copies them
  // to dist/ and generates correct content-hashed URLs.
  assetsInclude: ['**/*.wasm'],
  vitest: {
    coverage: {
      provider: 'v8',
      reporter: ['text', 'html'],
      thresholds: {
        statements: 100,
        branches: 100,
        functions: 100,
        lines: 100
      }
    }
  },
  server: {
    port: 5173
  },
  // Ensure workers and code-split outputs use ES modules (avoid IIFE/UMD formats)
  worker: {
    format: 'es'
  },
  build: {
    rollupOptions: {
      output: {
        format: 'es'
      }
    }
  }
});
